deploy:
  stage: deploy
  only:
    - master
  before_script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa

  script:
    - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa     
  tags:
    - deploy