# Generated by Django 2.2.3 on 2019-08-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneLine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wisesaying',
            name='text',
        ),
        migrations.AddField(
            model_name='wisesaying',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='wisesaying',
            name='param1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='wisesaying',
            name='param2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='wisesaying',
            name='param3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='wisesaying',
            name='param4',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='wisesaying',
            name='param5',
            field=models.TextField(null=True),
        ),
    ]
